"""
export_rules.py - Export rules_default.yaml to JSON, for other (non-Python)
implementations of the credential-scrubber detection rules - e.g. the
browser-based JS port - to consume without duplicating the ruleset by hand.

Usage:
    python export_rules.py

Writes, next to this script:
    rules.json       - the rules, as plain JSON
    rules-data.js     - the same data, as `const RULES = {...}`, exposed as
                        `window.RULES` when run in a browser
"""
import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
RULES_YAML = HERE / "rules_default.yaml"
RULES_JSON = HERE / "rules.json"
RULES_JS = HERE / "rules-data.js"


def load_rules_raw(rules_path):
    with open(rules_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def write_json(rules, out_path):
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(rules, f, indent=2)
        f.write("\n")


def write_js(rules, out_path):
    body = json.dumps(rules, indent=2)
    js = (
        "// Auto-generated by export_rules.py from rules_default.yaml. Do not edit by hand.\n"
        f"const RULES = {body};\n"
        "\n"
        "if (typeof window !== \"undefined\") {\n"
        "  window.RULES = RULES;\n"
        "}\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js)


def main():
    rules = load_rules_raw(RULES_YAML)
    write_json(rules, RULES_JSON)
    write_js(rules, RULES_JS)
    print(f"Wrote {RULES_JSON}")
    print(f"Wrote {RULES_JS}")


if __name__ == "__main__":
    main()
